achievement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from achievement import views

app_name='achievement'

urlpatterns = [
    
    #home page ie "/blog/"
    path('',views.achievement,name='achievements'),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from blog import views

app_name='blog'

urlpatterns = [
    
    #home page ie "/blog/"
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/',views.detail,name='detail'),
]

experience/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from experience import views

app_name='experience'

urlpatterns = [
    
    #home page ie "/blog/"
    path('',views.experience,name='experiences'),
    
]

new_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('',views.home,name="home"),
    path('admin_kaushik_rina/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('portfolio/',include('portfolio.urls')),
    path('experience/',include('experience.urls')),
    path('achievement/',include('achievement.urls')),
    #path('codingProfile/',views.codingProfile,name="codingProfile"),
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#https://drive.google.com/uc?export=view&id=1WrrwAn50_I_0lCV_AMxsZHMXiNerx6mB
#http://drive.google.com/uc?export=view&id=1yz6ZSUqSiP6bM0Uc-Wz3pb51nwWgn_4Y

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

app_name='portfolio'

urlpatterns = [
    
    #home page ie "/portfolio/"
    path('',views.allProjects,name='allProjects'),
    path('<int:projectId>/',views.detailProject,name='detailProject'),
    path('codingProfile/',views.codingProfile,name="codingProfile"),

]

achievement/models.py
from django.db import models

# Create your models here.
class Achievement(models.Model):
    description = models.TextField()
    date = models.CharField(max_length=30)
    url = models.URLField(blank=True)
    #image = models.ImageField(upload_to='portfolio/images/')
    


    #the below function actually shows the name of the objects as object's title instead of blog(0),blog(1),etc
    def __str__(self):
    	return self.description

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    #image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)
    date = models.DateField(auto_now=True)


    #the below function actually shows the name of the objects as object's title instead of blog(0),blog(1),etc
    def __str__(self):
    	return self.title
        

experience/models.py
from django.db import models

# Create your models here.
class Experience(models.Model):
    companyName = models.CharField(max_length=200)
    date=models.CharField(max_length=30)
    designation=models.CharField(max_length=100)
    description = models.TextField()
    #image = models.ImageField(upload_to='portfolio/images/')
    


    #the below function actually shows the name of the objects as object's title instead of blog(0),blog(1),etc
    def __str__(self):
    	return self.companyName

portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    # title = models.CharField(max_length=100)
    # description = models.CharField(max_length=600)
    # image = models.ImageField(upload_to='portfolio/images/')
    # url = models.URLField(blank=True)

    title = models.CharField(max_length=100)
    shortDescription = models.CharField(max_length=600,default='')
    longDescription = models.TextField(default='')
    startDate=models.DateField()
    endDate=models.DateField()
    techStack=models.TextField(default='')
    #image = models.ImageField(upload_to='portfolio/images/')
    imageurl= models.URLField(blank=True)
    githubUrl = models.URLField(blank=True)
    liveUrl=models.URLField(blank=True)




    #the below function actually shows the name of the objects as object's title instead of project(0),project(1),etc
    def __str__(self):
    	return self.title
        

achievement/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from .models import Achievement


def achievement(request):
    achievements = Achievement.objects.all()
    return render(request,"achievements.html",{'achievements':achievements})

blog/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from .models import Blog


def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request,"all_blogs.html",{'blogs':blogs})


def detail(request,blog_id):
    blog=get_object_or_404(Blog, pk=blog_id)
    return render(request,"detail.html",{'blog':blog})

experience/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from .models import Experience


def experience(request):
    experiences = Experience.objects.order_by('-date')
    return render(request,"experiences.html",{'experiences':experiences})

portfolio/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.

#import project model here
from .models import Project
def home(request):
    #grab all the project objects here
    #projects= Project.objects.all()[0].title
    projects= Project.objects.all()
    return render(request,'home.html',{'projects':projects})


def codingProfile(request):
    return render(request,'codingProfile.html')


def allProjects(request):
    projects= Project.objects.all()
    return render(request,'allProjects.html',{'projects':projects})


def detailProject(request,projectId):
    project=get_object_or_404(Project,pk=projectId)
    return render(request,'detailProject.html',{'project':project})

templates/achievements.html
{% extends 'base2.html' %}

{% block content %}

<h1 style="text-align: center;">ACHIEVEMENTS</h1>
<!--{{blogs.count|pluralize}}...if no of blog is 1 then it shows 1 blog and if number is greater than 1 then show 3 blogs or 4 blogs-->


{% for achievement in achievements%}

<!---this was not working <a href="blog/{{blog.pk}}/" ><h2>{{blog.title}}</h2></a>-->

<!--This was working:<a href="./{{blog.pk}}/" ><h2>{{blog.title}}</h2></a> -->

<!--In below line, blog:detail...here blog is app name and detail is the url name in urls.py...the app_name is written in urls.py of blog app-->

<p>⁕ {{achievement.description|safe}}<br>{{achievement.date}}</p>


<br><br>

{% endfor %}

{% endblock %}

templates/allProjects.html
{% extends 'base2.html' %}

{% block content %}

<h1 style="text-align: center;">ALL PROJECTS</h1>
<!--{{blogs.count|pluralize}}...if no of blog is 1 then it shows 1 blog and if number is greater than 1 then show 3 blogs or 4 blogs-->
<h2>Kaushik has done {{projects.count}} project{{projects.count|pluralize}}</h2>
{% for project in projects %}

<!---this was not working <a href="blog/{{blog.pk}}/" ><h2>{{blog.title}}</h2></a>-->

<!--This was working:<a href="./{{blog.pk}}/" ><h2>{{blog.title}}</h2></a> -->

<!--In below line, blog:detail...here blog is app name and detail is the url name in urls.py...the app_name is written in urls.py of blog app-->
<div >
<a href="{% url 'portfolio:detailProject' project.id %}" ><h2>{{project.title}}</h2></a>

<p>{{project.description| striptags|truncatechars:50}}</p><br><br>
</div>

{% endfor %}

{% endblock %}

templates/all_blogs.html
{% extends 'base2.html' %}

{% block content %}

<h1 style="text-align: center;">ALL BLOGS</h1>
<!--{{blogs.count|pluralize}}...if no of blog is 1 then it shows 1 blog and if number is greater than 1 then show 3 blogs or 4 blogs-->
<h2>Kaushik has written {{blogs.count}} blog{{blogs.count|pluralize}}</h2>
{% for blog in blogs %}

<!---this was not working <a href="blog/{{blog.pk}}/" ><h2>{{blog.title}}</h2></a>-->

<!--This was working:<a href="./{{blog.pk}}/" ><h2>{{blog.title}}</h2></a> -->

<!--In below line, blog:detail...here blog is app name and detail is the url name in urls.py...the app_name is written in urls.py of blog app-->
<div >
<a href="{% url 'blog:detail' blog.id %}" ><h2>{{blog.title}}</h2></a>
<h5>{{blog.date}}</h5>
<p>{{blog.description| striptags|truncatechars:60}}</p><br><br>
</div>

{% endfor %}

{% endblock %}

templates/base2.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{% static 'portfolio/custom.css' %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  

  <title>KAUSHIK MAHAJAN</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light" style="background-color: #e3f2fd;">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        
        <span>KAUSHIK MAHAJAN</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="https://drive.google.com/file/d/1TfWrdSWK-hRy6TqA4yK_c-dFoeu4LkWw/view?usp=sharing" target="_blank">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'experience:experiences' %}" target="_blank">Experience</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/kaushik-mahajan-39427a1b2/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}#projects" >Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'achievement:achievements' %}" >Achievements</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'portfolio:codingProfile' %}" target="_blank">Coding Profiles</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

templates/codingProfile.html
{% extends 'base2.html' %}

{% block content %}

<h1 style="text-align: center;">Coding Profiles</h1>

	<h2><a href="https://leetcode.com/kaushikm2k/" target="_blank" >Leetcode</a></h2><br>
	<h2><a href="https://github.com/kaushikMJ" target="_blank" >Github</a></h2><br>
	<h2><a href="https://codeforces.com/profile/KaushikMn" target="_blank" >Codeforces</a></h2><br>
	


{% endblock %}

templates/detail.html
{% extends 'base2.html' %}

{% block content %}

<h1>{{blog.title}}</h1>
<h5>--{{blog.date|date:'d'}} {{blog.date|date:'M'}} , {{blog.date|date:'Y'}}--</h5>
<p>{{blog.description|safe}}</p>


{% endblock %}

templates/detailProject.html
{% extends 'base2.html' %}

{% block content %}

<p><h1>{{project.title}}</h1> &nbsp&nbsp <h5>
	{% if project.liveUrl %}
	<a href="{{project.liveUrl}}">Live</a> 
	{% endif %}
&nbsp</h5><h5><a href="{{project.githubUrl}}">Github</a> &nbsp</h5></p>
<h5>{{project.startDate|date:'M'}} , {{project.startDate|date:'Y'}} --- {{project.endDate|date:'M'}} , {{project.endDate|date:'Y'}}</h5>


<p>{{project.longDescription|safe}}</p>
<br>
<p>Tech Stack : <b>{{project.techStack|safe}}</b></p>
{% endblock %}

templates/experiences.html
{% extends 'base2.html' %}

{% block content %}

<h1 style="text-align: center;">EXPERIENCES</h1>
<!--{{blogs.count|pluralize}}...if no of blog is 1 then it shows 1 blog and if number is greater than 1 then show 3 blogs or 4 blogs-->

{% for experience in experiences %}

<!---this was not working <a href="blog/{{blog.pk}}/" ><h2>{{blog.title}}</h2></a>-->

<!--This was working:<a href="./{{blog.pk}}/" ><h2>{{blog.title}}</h2></a> -->

<!--In below line, blog:detail...here blog is app name and detail is the url name in urls.py...the app_name is written in urls.py of blog app-->


	<div >
		<h2>{{experience.companyName}}</h2>
		<p><b>{{experience.designation}}</b> &nbsp &nbsp &nbsp {{experience.date}}</p>
		<p>{{experience.description| striptags|truncatechars:50}}</p><br><br>
		
	</div>

<br><br>
{% endfor %}

{% endblock %}

templates/home.html
{% extends "base2.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/resumePic.jpg' %}" class=" center" height="300" width="800">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1  class="font-weight-bold">Kaushik Mahajan is an aspiring Software Developer .<br>He loves problem solving.<br>😊</h1>
  </div>
</div>


<div id="projects">
  <h2 class="mt-5">Portfolio Projects</h2>
  <hr>
  <div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-md-6">

      <!-- {% if project.url %}
      <a href="{{ project.url }}">
        {% if project.image.url %}
        <img src="{{ project.image.url }}" class="img-fluid mb-2">
        {% endif %}
      </a>
      {% else %}

      <img src="{{ project.image.url }}" class="img-fluid mb-2">
      {% endif %}
      <a href="{% url 'portfolio:detailProject' project.id %}"><h3>{{ project.title }}</h3></a>
      <p>{{ project.shortDescription|safe}}</p> -->

      <img src="{{ project.imageurl }}" class="img-fluid mb-2">
      
      <a href="{% url 'portfolio:detailProject' project.id %}"><h3>{{ project.title }}</h3></a>
      <p>{{ project.shortDescription|safe}}</p>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}